name: react-rust-postgres
services:
  frontend:
    build:
      context: ../frontend
      target: builder
    networks:
      - client-side
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    build:
      context: ../backend
      target: builder
    networks:
      - client-side
      - server-side
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db

  db:
    build:
      context: ../db
    restart: always
    networks:
      - server-side
    ports:
      - 5433:5432
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  client-side: {}
  server-side: {}

volumes:
  backend-cache: {}
  db-data: {}
